version: '3.8'

networks:
  web:
    external: true
  internal:
    external: false
    
services:
  bjb_web:
    container_name: bjb_web
    build: 
      context: ./
      dockerfile: Dockerfile
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bjb_web.rule=Host(`bjbaskar.com`, `www.bjbaskar.com`)"
        - "traefik.http.routers.bjb_web.tls.certresolver=letsencrypt"
        - "traefik.http.routers.blog.tls=true"     
    expose:
      - 5000
    networks:
      - internal
      - web
    restart: always

  bjb_traefik:
    image: traefik:v2.4
    container_name: bjb_traefik 
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.prod.toml:/etc/traefik/traefik.toml"
