[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http]
    [entryPoints.websecure.http.tls]
      [entryPoints.websecure.http.tls.domains]
        main = "bjbaskar.com"
        sans = ["thirukkural.bjbaskar.com", "api.bjbaskar.com"]

[accessLog]
	format = "json"

[log]
	level = "DEBUG"
	format = "json"

[api]
	dashboard = true
	insecure = true

[providers]
  [providers.docker]
    exposedByDefault = false
    watch = true
    network = "web"

[certificatesResolvers.letsencrypt.acme]
  email = "bjbaskar@gmail.com"
  storage= "acme.json"
  tlschallenge = true
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"
