[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[accessLog]
	format = "json"

[log]
	level = "DEBUG"
	format = "json"

[api]
	dashboard = true
	insecure = true

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "bjbaskar@gmail.com"
  storage= "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"

[[acme.domains]]
   main = "bjbaskar.com"
   sans = ["thirukkural.bjbaskar.com", "api.bjbaskar.com"]