[http.middlewares.simpleAuth.basicAuth]
users = ["admin:$apr1$K3OfSAhl$TJyCWgPkvDFCXTvwtmeka0"]

[http.routers.api]
rule = "Host(`monitor.bjbaskar.com`)"
entrypoints = ["websecure"]
middlewares = ["simpleAuth"]
service = "api@internal"

[http.routers.api.tls]
certResolver = "myresolver"
